# Context Orchestrator - PowerShell CLI Recording Wrapper
# Automatically wraps claude/codex commands to record sessions

<#
.SYNOPSIS
    Setup CLI recording wrapper for Context Orchestrator

.DESCRIPTION
    This script installs PowerShell functions that wrap claude/codex commands
    to automatically record sessions to Context Orchestrator.

.PARAMETER Install
    Install the wrapper functions to PowerShell profile

.PARAMETER Uninstall
    Remove the wrapper functions from PowerShell profile

.EXAMPLE
    .\setup_cli_recording.ps1 -Install
#>

param(
    [switch]$Install,
    [switch]$Uninstall
)

$WrapperFunctions = @'
# Context Orchestrator CLI Recording Wrapper
# Generated by setup_cli_recording.ps1

# Check if we're in an internal call (prevent recursion)
function Test-IsInternalCall {
    return $env:CONTEXT_ORCHESTRATOR_INTERNAL -eq "1"
}

# Generate session ID
function New-SessionId {
    return "session-$(Get-Date -Format 'yyyyMMdd-HHmmss')-$([guid]::NewGuid().ToString().Substring(0,8))"
}

# Send command to Context Orchestrator (async)
function Send-ToContextOrchestrator {
    param(
        [string]$SessionId,
        [string]$Command,
        [string]$Output,
        [int]$ExitCode
    )

    # Skip if internal call
    if (Test-IsInternalCall) {
        return
    }

    # Build JSON payload
    $payload = @{
        jsonrpc = "2.0"
        id = 1
        method = "add_command"
        params = @{
            session_id = $SessionId
            command = $Command
            output = $Output
            exit_code = $ExitCode
        }
    } | ConvertTo-Json -Compress

    # Send to Context Orchestrator in background job
    Start-Job -ScriptBlock {
        param($payload)

        try {
            # Find Python
            $python = Get-Command python -ErrorAction SilentlyContinue

            if ($python) {
                # Set internal flag to prevent recursion
                $env:CONTEXT_ORCHESTRATOR_INTERNAL = "1"

                # Send to Context Orchestrator
                $payload | & $python.Source -m src.main 2>&1 | Out-Null
            }
        }
        catch {
            # Silently fail (don't interrupt user workflow)
        }
    } -ArgumentList $payload | Out-Null
}

# Wrapper for claude command
function claude {
    # Check if internal call
    if (Test-IsInternalCall) {
        # Call real claude
        & claude.exe @args
        return
    }

    # Generate session ID
    $sessionId = New-SessionId()

    # Capture command
    $command = "claude $($args -join ' ')"

    # Call real claude and capture output
    $output = & claude.exe @args 2>&1 | Tee-Object -Variable capturedOutput

    # Get exit code
    $exitCode = $LASTEXITCODE

    # Send to Context Orchestrator
    Send-ToContextOrchestrator -SessionId $sessionId -Command $command -Output ($capturedOutput -join "`n") -ExitCode $exitCode

    # Return exit code
    return $exitCode
}

# Wrapper for codex command
function codex {
    # Check if internal call
    if (Test-IsInternalCall) {
        # Call real codex
        & codex.exe @args
        return
    }

    # Generate session ID
    $sessionId = New-SessionId()

    # Capture command
    $command = "codex $($args -join ' ')"

    # Call real codex and capture output
    $output = & codex.exe @args 2>&1 | Tee-Object -Variable capturedOutput

    # Get exit code
    $exitCode = $LASTEXITCODE

    # Send to Context Orchestrator
    Send-ToContextOrchestrator -SessionId $sessionId -Command $command -Output ($capturedOutput -join "`n") -ExitCode $exitCode

    # Return exit code
    return $exitCode
}

Write-Host "Context Orchestrator CLI recording enabled" -ForegroundColor Green
'@

function Install-Wrapper {
    Write-Host "Installing Context Orchestrator CLI recording wrapper..." -ForegroundColor Cyan

    # Check if profile exists
    if (-not (Test-Path $PROFILE)) {
        Write-Host "Creating PowerShell profile: $PROFILE" -ForegroundColor Yellow
        New-Item -Path $PROFILE -ItemType File -Force | Out-Null
    }

    # Read current profile
    $profileContent = Get-Content -Path $PROFILE -Raw -ErrorAction SilentlyContinue

    # Check if already installed
    if ($profileContent -match "Context Orchestrator CLI Recording Wrapper") {
        Write-Host "Wrapper already installed" -ForegroundColor Yellow
        return
    }

    # Append wrapper functions
    Add-Content -Path $PROFILE -Value "`n$WrapperFunctions"

    Write-Host "✓ Wrapper installed to: $PROFILE" -ForegroundColor Green
    Write-Host ""
    Write-Host "Please restart PowerShell or run: . `$PROFILE" -ForegroundColor Yellow
}

function Uninstall-Wrapper {
    Write-Host "Uninstalling Context Orchestrator CLI recording wrapper..." -ForegroundColor Cyan

    # Check if profile exists
    if (-not (Test-Path $PROFILE)) {
        Write-Host "No profile found, nothing to uninstall" -ForegroundColor Yellow
        return
    }

    # Read current profile
    $profileContent = Get-Content -Path $PROFILE -Raw

    # Check if installed
    if ($profileContent -notmatch "Context Orchestrator CLI Recording Wrapper") {
        Write-Host "Wrapper not installed" -ForegroundColor Yellow
        return
    }

    # Remove wrapper section
    $newContent = $profileContent -replace "(?s)# Context Orchestrator CLI Recording Wrapper.*?Write-Host `"Context Orchestrator CLI recording enabled`".*?\n", ""

    # Write back
    Set-Content -Path $PROFILE -Value $newContent

    Write-Host "✓ Wrapper uninstalled from: $PROFILE" -ForegroundColor Green
    Write-Host ""
    Write-Host "Please restart PowerShell" -ForegroundColor Yellow
}

# Main
if ($Install) {
    Install-Wrapper
}
elseif ($Uninstall) {
    Uninstall-Wrapper
}
else {
    Write-Host "Usage:"
    Write-Host "  Install:   .\setup_cli_recording.ps1 -Install"
    Write-Host "  Uninstall: .\setup_cli_recording.ps1 -Uninstall"
}
